"""
This module contains all the code related to the InferNET library. This module is responsible for
taking the data generated by the pre-processing data module and using it to train a neural network
that will be used to produce inferred immediate rewards from the delayed rewards.
"""
