"""
The src/ directory contains the source code for the Pyrenees pipeline. The pipeline is divided into
several stages, each of which is implemented in a separate subdirectory. The pipeline stages are as
follows:

    - pre-processing
    - policy
    - evaluation (optional)
    - post-processing (to be implemented)
    - analysis (to be implemented)

Each of these stages is implemented in a separate subdirectory. Each subdirectory contains a
__init__.py file, which contains a docstring that describes the purpose of the subdirectory. For
example, the docstring for src/policy/__init__.py is as follows:

    This module contains all code related to Pyrenees policies.

The docstrings for the other __init__.py files are similar. The docstrings for the __init__.py
files in the subdirectories of src/preprocess/ are as follows:

    - src/preprocess/data/__init__.py:
        The pre-processing of the data occurs in this module. This module is responsible for taking
        the raw data and converting it into a format that can be used by the rest of the pipeline.
        This module is also responsible for generating the necessary data structures that are
        required by the rest of the pipeline.

    - src/preprocess/infernet/__init__.py:
        This module contains all the code related to the InferNET library. This module is
        responsible for taking the data generated by the pre-processing data module and using it to
        train a neural network that will be used to produce inferred immediate rewards from the
        delayed rewards.
"""
