data:
  features:
    basic:
      - recordID
      - answerID
      - time
      - userID
      - problem
      - decisionID
      - decisionPoint
      - decisionOrdering
      - substepMode
      - KC
      - session
      - substepOrdering
    problem:
      - ntellsSinceElicit
      - ntellsSinceElicitKC
      - nElicitSinceTell
      - nElicitSinceTellKC
      - pctElicit
      - pctElicitKC
      - pctElicitSession
      - pctElicitKCSession
      - nTellSession
      - nTellKCSession
      - kcOrdering
      - kcOrderingSession
      - durationKCBetweenDecision
      - timeInSession
      - timeBetweenSession
      - timeOnTutoring
      - timeOnTutoringWE
      - timeOnTutoringPS
      - timeOnTutoringKC
      - timeOnTutoringKCWE
      - timeOnTutoringKCPS
      - avgTimeOnStep
      - avgTimeOnStepWE
      - avgTimeOnStepPS
      - avgTimeOnStepKC
      - avgTimeOnStepKCWE
      - avgTimeOnStepKCPS
      - timeOnLastStepKCPS
      - timeOnTutoringSession
      - timeOnTutoringSessionWE
      - timeOnTutoringSessionPS
      - avgTimeOnStepSession
      - avgTimeOnStepSessionWE
      - avgTimeOnStepSessionPS
      - nTotalHint
      - nTotalHintSession
      - nHintKC
      - nHintSessionKC
      - AvgTimeOnStepWithHint
      - durationSinceLastHint
      - stepsSinceLastHint
      - stepsSinceLastHintKC
      - totalTimeStepsHint
      - totalStepsHint
      - earlyTraining
      - simpleProblem
      - nKCs
      - nKCsAsPS
      - nKCsSession
      - nKCsSessionPS
      - newLevelDifficulty
      - nPrincipleInProblem
      - quantitativeDegree
      - nTutorConceptsSession
      - tutAverageConcepts
      - tutAverageConceptsSession
      - tutConceptsToWords
      - tutConceptsToWordsSession
      - tutAverageWords
      - tutAverageWordsSession
      - tutAverageWordsPS
      - tutAverageWordsSessionPS
      - nDistinctPrincipleInSession
      - nPrincipleInSession
      - problemDifficuly
      - problemCompexity
      - problemCategory
      - pctCorrect
      - pctOverallCorrect
      - nCorrectKC
      - nIncorrectKC
      - pctCorrectKC
      - pctOverallCorrectKC
      - nCorrectKCSession
      - nIncorrectKCSession
      - pctCorrectSession
      - pctCorrectKCSession
      - pctOverallCorrectSession
      - pctOverallCorrectKCSession
      - nStepSinceLastWrong
      - nStepSinceLastWrongKC
      - nWEStepSinceLastWrong
      - nWEStepSinceLastWrongKC
      - nStepSinceLastWrongSession
      - nStepSinceLastWrongKCSession
      - nWEStepSinceLastWrongSession
      - nWEStepSinceLastWrongKCSession
      - timeSinceLastWrongStepKC
      - nCorrectPSStepSinceLastWrong
      - nCorrectPSStepSinceLastWrongKC
      - nCorrectPSStepSinceLastWrongKCSession
      - pctCorrectPrin
      - pctCorrectPrinSession
      - nStepSinceLastWrongPrin
      - nWEStepSinceLastWrongPrin
      - nStepSinceLastWrongPrinSession
      - nWEStepSinceLastWrongPrinSession
      - nCorrectPSStepSinceLastWrongPrin
      - nCorrectPSStepSinceLastWrongPrinSession
      - pctCorrectFirst
      - nStepsSinceLastWrongFirst
      - nWEStepSinceLastWrongFirst
      - nCorrectPSStepSinceLastWrongFirst
      - pctCorrectLastProb
      - pctCorrectLastProbPrin
      - pctCorrectAdd2Select
      - pctCorrectAdd3Select
      - pctCorrectCompSelect
      - pctCorrectDeMorSelect
      - pctCorrectIndeSelect
      - pctCorrectMutualSelect
      - pctCorrectAdd2Apply
      - pctCorrectAdd3Apply
      - pctCorrectCompApply
      - pctCorrectDeMorApply
      - pctCorrectIndeApply
      - pctCorrectMutualApply
      - pctCorrectAdd2All
      - pctCorrectAdd3All
      - pctCorrectCompAll
      - pctCorrectDeMorAll
      - pctCorrectIndeAll
      - pctCorrectMutualAll
      - pctCorrectSelectMain
      - nAdd2Prob
      - nAdd3Prob
      - nDeMorProb
      - nIndeProb
      - nCompProb
      - nMutualProb

    step:
      - ntellsSinceElicit
      - ntellsSinceElicitKC
      - nElicitSinceTell
      - nElicitSinceTellKC
      - pctElicit
      - pctElicitKC
      - pctElicitSession
      - pctElicitKCSession
      - nTellSession
      - nTellKCSession
      - kcOrdering
      - kcOrderingSession
      - kcOrderingPb
      - durationKCBetweenDecision
      - timeInSession
      - timeBetweenSession
      - timeOnCurrentProblem
      - timeOnTutoring
      - timeOnTutoringWE
      - timeOnTutoringPS
      - timeOnTutoringKC
      - timeOnTutoringKCWE
      - timeOnTutoringKCPS
      - avgTimeOnStep
      - avgTimeOnStepWE
      - avgTimeOnStepPS
      - avgTimeOnStepKC
      - avgTimeOnStepKCWE
      - avgTimeOnStepKCPS
      - timeOnLastStepKCPS
      - timeOnTutoringSession
      - timeOnTutoringSessionWE
      - timeOnTutoringSessionPS
      - avgTimeOnStepSession
      - avgTimeOnStepSessionWE
      - avgTimeOnStepSessionPS
      - timeOnTutoringProblem
      - timeOnTutoringProblemWE
      - timeOnTutoringProblemPS
      - avgTimeOnStepProblem
      - avgTimeOnStepProblemWE
      - avgTimeOnStepProblemPS
      - nTotalHint
      - nTotalHintSession
      - nHintKC
      - nHintSessionKC
      - nTotalHintProblem
      - AvgTimeOnStepWithHint
      - durationSinceLastHint
      - stepsSinceLastHint
      - stepsSinceLastHintKC
      - totalTimeStepsHint
      - totalStepsHint
      - earlyTraining
      - simpleProblem
      - nKCs
      - nKCsAsPS
      - nKCsSession
      - nKCsSessionPS
      - newLevelDifficulty
      - performanceDifficulty
      - nPrincipleInProblem
      - quantitativeDegree
      - nTutorConceptsSession
      - tutAverageConcepts
      - tutAverageConceptsSession
      - tutConceptsToWords
      - tutConceptsToWordsSession
      - tutAverageWords
      - tutAverageWordsSession
      - tutAverageWordsPS
      - tutAverageWordsSessionPS
      - nDistinctPrincipleInSession
      - nPrincipleInSession
      - principleDifficulty
      - principleCategory
      - problemDifficuly
      - problemCompexity
      - problemCategory
      - pctCorrect
      - pctOverallCorrect
      - nCorrectKC
      - nIncorrectKC
      - pctCorrectKC
      - pctOverallCorrectKC
      - nCorrectKCSession
      - nIncorrectKCSession
      - pctCorrectSession
      - pctCorrectKCSession
      - pctOverallCorrectSession
      - pctOverallCorrectKCSession
      - nStepSinceLastWrong
      - nStepSinceLastWrongKC
      - nWEStepSinceLastWrong
      - nWEStepSinceLastWrongKC
      - nStepSinceLastWrongSession
      - nStepSinceLastWrongKCSession
      - nWEStepSinceLastWrongSession
      - nWEStepSinceLastWrongKCSession
      - timeSinceLastWrongStepKC
      - nCorrectPSStepSinceLastWrong
      - nCorrectPSStepSinceLastWrongKC
      - nCorrectPSStepSinceLastWrongKCSession
      - pctCorrectPrin
      - pctCorrectPrinSession
      - nStepSinceLastWrongPrin
      - nWEStepSinceLastWrongPrin
      - nStepSinceLastWrongPrinSession
      - nWEStepSinceLastWrongPrinSession
      - nCorrectPSStepSinceLastWrongPrin
      - nCorrectPSStepSinceLastWrongPrinSession
      - pctCorrectFirst
      - nStepsSinceLastWrongFirst
      - nWEStepSinceLastWrongFirst
      - nCorrectPSStepSinceLastWrongFirst
      - pctCorrectLastProb
      - pctCorrectLastProbPrin
      - pctCorrectAdd2Select
      - pctCorrectAdd3Select
      - pctCorrectCompSelect
      - pctCorrectDeMorSelect
      - pctCorrectIndeSelect
      - pctCorrectMutualSelect
      - pctCorrectAdd2Apply
      - pctCorrectAdd3Apply
      - pctCorrectCompApply
      - pctCorrectDeMorApply
      - pctCorrectIndeApply
      - pctCorrectMutualApply
      - pctCorrectAdd2All
      - pctCorrectAdd3All
      - pctCorrectCompAll
      - pctCorrectDeMorAll
      - pctCorrectIndeAll
      - pctCorrectMutualAll
      - pctCorrectSelectMain
      - nAdd2Prob
      - nAdd3Prob
      - nDeMorProb
      - nIndeProb
      - nCompProb
      - nMutualProb
