name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v3
      with:  # https://stackoverflow.com/questions/59271919/how-to-clone-public-submodule-in-github-actions
        submodules: true  # change to recursive if submodules require another submodule
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pip==23.1.1
        python -m pip install wheel==0.38.4
        python -m pip install setuptools==65.5.0
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install -e .
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files 'Pyrenees-Pipeline/*.py')
